In [1]:
from detRule import DetRule
import numpy as np
np.random.seed(73)

<h4>Generate random matrices</h4>

In [14]:
n= 3 # matrix of shape nxn
scale = 10 # to increase number of terms
a = np.round(scale*np.random.rand(n,n))
b = np.round(scale*np.random.rand(n,n))
c = np.round(scale*np.random.rand(n,n))
a,b,c

(array([[ 3., 10.,  9.],
        [ 8.,  7.,  1.],
        [ 7.,  6.,  6.]]),
 array([[1., 2., 5.],
        [5., 1., 4.],
        [7., 7., 1.]]),
 array([[0., 3., 8.],
        [6., 1., 3.],
        [6., 4., 6.]]))

<h4>Pass "t" number of Matrices Into DetRule Class</h4>

In [3]:
rule = DetRule(a,b,c)

<h4>Converts rank 2 Tensors (Matrices) into Rank 3 Tensor</h4>

In [4]:
rule.mats

array([[[ 6.,  5.,  5.],
        [ 6.,  5.,  2.],
        [ 2.,  6.,  8.]],

       [[ 3.,  4.,  6.],
        [ 2.,  9.,  2.],
        [ 6.,  3.,  9.]],

       [[ 9.,  1., 10.],
        [ 0.,  0.,  5.],
        [ 0.,  3.,  2.]]])

<h4>Check the number of matrices and its Shape</h4>

In [5]:
t,row,col = rule.shape
t,row,col

(3, 3, 3)

<h4>Check Number of Terms</h4>

In [6]:
rule.terms

27

<h4>Add all Matrices</h4>

In [7]:
rule.addMats

array([[18., 10., 21.],
       [ 8., 14.,  9.],
       [ 8., 12., 19.]])

<h4>Find det of added Matrices</h4>

In [8]:
rule.addedMatsDet

1707.9999999999993

<h4>Find det of indivisulal matrices</h4>

In [9]:
rule.matsDet , sum(rule.matsDet)

([78.0, -87.0, -135.00000000000003], -144.00000000000003)

<h4>Get All Combinational Matrices</h4>

In [10]:
for com in rule.ComMats(): print(com)

[[6. 5. 5.]
 [6. 5. 2.]
 [2. 6. 8.]]
[[6. 5. 5.]
 [6. 5. 2.]
 [6. 3. 9.]]
[[6. 5. 5.]
 [6. 5. 2.]
 [0. 3. 2.]]
[[6. 5. 5.]
 [2. 9. 2.]
 [2. 6. 8.]]
[[6. 5. 5.]
 [2. 9. 2.]
 [6. 3. 9.]]
[[6. 5. 5.]
 [2. 9. 2.]
 [0. 3. 2.]]
[[6. 5. 5.]
 [0. 0. 5.]
 [2. 6. 8.]]
[[6. 5. 5.]
 [0. 0. 5.]
 [6. 3. 9.]]
[[6. 5. 5.]
 [0. 0. 5.]
 [0. 3. 2.]]
[[3. 4. 6.]
 [6. 5. 2.]
 [2. 6. 8.]]
[[3. 4. 6.]
 [6. 5. 2.]
 [6. 3. 9.]]
[[3. 4. 6.]
 [6. 5. 2.]
 [0. 3. 2.]]
[[3. 4. 6.]
 [2. 9. 2.]
 [2. 6. 8.]]
[[3. 4. 6.]
 [2. 9. 2.]
 [6. 3. 9.]]
[[3. 4. 6.]
 [2. 9. 2.]
 [0. 3. 2.]]
[[3. 4. 6.]
 [0. 0. 5.]
 [2. 6. 8.]]
[[3. 4. 6.]
 [0. 0. 5.]
 [6. 3. 9.]]
[[3. 4. 6.]
 [0. 0. 5.]
 [0. 3. 2.]]
[[ 9.  1. 10.]
 [ 6.  5.  2.]
 [ 2.  6.  8.]]
[[ 9.  1. 10.]
 [ 6.  5.  2.]
 [ 6.  3.  9.]]
[[ 9.  1. 10.]
 [ 6.  5.  2.]
 [ 0.  3.  2.]]
[[ 9.  1. 10.]
 [ 2.  9.  2.]
 [ 2.  6.  8.]]
[[ 9.  1. 10.]
 [ 2.  9.  2.]
 [ 6.  3.  9.]]
[[ 9.  1. 10.]
 [ 2.  9.  2.]
 [ 0.  3.  2.]]
[[ 9.  1. 10.]
 [ 0.  0.  5.]
 [ 2.  6.  8.]]
[[ 9.  1. 10

<h4>Get Det of All Combinations</h4>

In [11]:
for comdet in rule.ComMatsDet(): print(comdet)

78.0
-36.0
54.00000000000001
270.00000000000006
180.0
82.00000000000001
-129.99999999999997
59.999999999999986
-90.0
64.00000000000003
-123.00000000000006
72.0
95.99999999999999
-87.0
56.00000000000002
-50.000000000000014
74.99999999999997
-44.99999999999999
468.00000000000017
189.00000000000003
203.99999999999994
468.00000000000017
189.0000000000002
164.0000000000002
-259.99999999999994
-105.00000000000006
-135.00000000000003


<h4>Sum All the Combinational det</h4>

In [12]:
rule.ComMatDetResult()

1708.0000000000005

<h4>Validate Sum det vs Combinational Det</h4>

In [13]:
sum_det = rule.addedMatsDet
com_det = rule.ComMatDetResult()
error = sum_det-com_det

print(f"sum det :{sum_det}\ncom det {com_det} \nerror {error}")

sum det :1707.9999999999993
com det 1708.0000000000005 
error -1.1368683772161603e-12
